---
- hosts: localhost

  become: true

  vars:
    username: deversma
    ssh_server: ovpn-phx2.redhat.com
    ssh_port: 330
    proxy_port: 9999

  vars_prompt:
    - name: "passcode"
      prompt: "What is your passcode (pin + token)?"

  tasks:
    - name: install prerequisite non "RH internal" packages
      dnf:
        name: "{{item}}"
        state: latest
        disablerepo: "rhel7-csb-stage"
      with_items:
        - openvpn
        - NetworkManager-openvpn-gnome

    - name: check for existing tunnel
      shell: ps -ef | grep -iE -- "ss[h].*{{proxy_port}}" | awk '{print $2}'
      register: proxy_pids

    - debug:
        msg: "Proxy detected running on {{proxy_port}} PIDs:{{proxy_pids.stdout}}"
      when: proxy_pids.stdout != ""

    - name: start ssh tunnel
      shell: |
        set +H
        nohup sshpass -p {{passcode}} ssh -D {{proxy_port}} {{username}}@{{ssh_server}} -p {{ssh_port}} -N &
        sleep 5
      when: proxy_pids.stdout == ""
      notify:
        - stop ssh tunnel

    # rpm_key, yum and dnf modules don't play nicely with environment setting http_proxy in Ansible
    - name: do proxy tasks (need to fix)
      shell: |
        http_proxy=socks5h://localhost:{{proxy_port}} rpm --import http://hdn.corp.redhat.com/rhel7-csb-stage/RPM-GPG-KEY-helpdesk
        http_proxy=socks5h://localhost:{{proxy_port}} curl -o /etc/yum.repos.d/rhel7-csb-stage.repo http://hdn.corp.redhat.com/rhel7-csb-stage/rhel7-csb-stage.repo
        http_proxy=socks5h://localhost:{{proxy_port}} yum install redhat-internal-cert-install redhat-internal-openvpn-profiles redhat-internal-NetworkManager-openvpn-profiles

  handlers:
    - name: stop ssh tunnel
      shell: ps -ef | grep -iE -- "ss[h].*{{proxy_port}}" | awk '{print $2}' | xargs kill -9
