---
- hosts: localhost

  become: true

  vars:
    username: deversma
    ssh_server: ovpn-phx2.redhat.com
    ssh_port: 330
    proxy_port: 9999
    proxy_env:
      http_proxy: http://localhost:8123
      https_proxy: https://localhost:8123

  vars_prompt:
    - name: "passcode"
      prompt: "What is your passcode (pin + token)?"

  tasks:
    - name: check for existing tunnel
      shell: ps -ef | grep -iE -- "ss[h].*{{proxy_port}}" | awk '{print $2}'
      register: proxy_pids

    - debug:
        msg: "Proxy detected running on {{proxy_port}} PIDs:{{proxy_pids.stdout}}"
      when: proxy_pids.stdout != ""

    - name: start ssh tunnel
      shell: |
        set +H
        nohup sshpass -p {{passcode}} ssh -D {{proxy_port}} {{username}}@{{ssh_server}} -p {{ssh_port}} -N &
        sleep 5
      when: proxy_pids.stdout == ""
      notify:
        - stop ssh tunnel

    - name: ensure git directory exists
      file:
        path: /home/{{username}}/git
        state: directory
        mode: 0775

    - name: download polipo
      git:
        repo: git@github.com:jech/polipo.git
        dest: /home/{{username}}/git

    - name: build polipo
      make:
        chdir: /home/{{username}}/git/polipo

    - name: start http proxy
      shell: nohup ./polipo socksParentProxy=localhost:9999 diskCacheRoot="" &
      args:
        chdir: /home/{{username}}/git/polipo
      notify:
          - stop http proxy


#    - name: do proxy tasks (need to fix)
#      shell: |
#        http_proxy=socks5h://localhost:{{proxy_port}} rpm --import http://hdn.corp.redhat.com/rhel7-csb-stage/RPM-GPG-KEY-helpdesk
#        http_proxy=socks5h://localhost:{{proxy_port}} curl -o /etc/yum.repos.d/rhel7-csb-stage.repo http://hdn.corp.redhat.com/rhel7-csb-stage/rhel7-csb-stage.repo
#        http_proxy=socks5h://localhost:{{proxy_port}} yum install openvpn NetworkManager-openvpn-gnome redhat-internal-cert-install redhat-internal-openvpn-profiles redhat-internal-NetworkManager-openvpn-profiles

    - rpm_key:
        state: present
        key: http://hdn.corp.redhat.com/rhel7-csb-stage/RPM-GPG-KEY-helpdesk
      environment: "{{proxy_env}}"

    - get_url:
        url: http://hdn.corp.redhat.com/rhel7-csb-stage/rhel7-csb-stage.repo
        dest: /etc/yum.repos.d/rhel7-csb-stage.repo
      environment: "{{proxy_env}}"

    - name: install non RH internal packages
      dnf:
        name: "{{item}}"
        state: latest
        disablerepo: "rhel7-csb-stage"
      with_items:
        - openvpn
        - NetworkManager-openvpn-gnome

    - name: install RH internal packages
      dnf:
        name: "{{item}}"
        state: latest
        disablerepo: "fedora,updates"
      with_items:
        - redhat-internal-cert-install
        - redhat-internal-openvpn-profiles
        - redhat-internal-NetworkManager-openvpn-profiles
      environment: "{{proxy_env}}"


  handlers:
    - name: stop ssh tunnel
      shell: ps -ef | grep -iE -- "ss[h].*{{proxy_port}}" | awk '{print $2}' | xargs kill -9

    - name: stop http proxy
      shell: ps -ef | grep -iE -- "polipo.*9999" | awk '{print $2}' | xargs kill -9
